engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - ff5e0a8290ef4e8117b036cc4812a6c6
    - 5982fb2894287cb052b91662cc970691
    config:
      languages:
      - javascript
ratings:
  paths:
  - lib/**